"""add_phoneNumber

Revision ID: 971f1e9c2359
Revises: 20214f3d9f49
Create Date: 2024-07-27 22:29:09.629043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971f1e9c2359'
down_revision: Union[str, None] = '20214f3d9f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
   
    # ### end Alembic commands ###
